---
- name: java_home
  command: echo $JAVA_HOME

- name: copy project to dest
  copy: src=/sumpay/admin/.jenkins/jobs/rong-admin-dev/workspace/sumpay-admin-web/target/admin.war   dest=/home/admin/temp/apache-tomcat-7.0.61/webapps/sumpay-admin-web.war  mode=0755
    



 
